 version: '2'
 services:
   db:
     image: postgres
   web:
     build: .
     volumes:
       - .:/code
     ports:
       - "8000:8000"
     depends_on:
       - db
     command: ["./wait-for-it.sh", "db:5432", "--", "sh", "setup_production.sh"]