 version: '2'
 services:
   db:
     image: postgres

   nginx:
     image: nginx:latest
     container_name: ng01
     ports:
       - "8000:8000"
     volumes:
       - ./config:/etc/nginx/conf.d
       - .:/code
     depends_on:
       - web

   web:
     image: lifeng2/mydjango
     build: .
     volumes:
       - .:/code
     depends_on:
       - db
     command: ["./wait-for-it.sh", "db:5432", "--", "sh", "setup_production.sh"]
     expose:
       - "8000"